## 練習時間
試著使用 sklearn datasets 的其他資料集 (wine, boston, ...)，來訓練自己的線性迴歸模型。

### HINT: 注意 label 的型態，確定資料集的目標是分類還是回歸，在使用正確的模型訓練！

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score

In [2]:
wine = datasets.load_wine()
boston = datasets.load_boston()
breast_cancer = datasets.load_breast_cancer()

In [3]:
print(wine.target[:10])
print(boston.target[:10])
print(breast_cancer.target[:10])

[0 0 0 0 0 0 0 0 0 0]
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9]
[0 0 0 0 0 0 0 0 0 0]


In [4]:
# Linear Regression

x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.1, random_state=4)

regr = linear_model.LinearRegression()
regr.fit(x_train, y_train)

y_pred = regr.predict(x_test)
print("Mean squared error: %.2f"% mean_squared_error(y_test, y_pred))

Mean squared error: 17.03


In [5]:
# Logistic Regression

x_train, x_test, y_train, y_test = train_test_split(wine.data, wine.target, test_size=0.1, random_state=4)

logreg = linear_model.LogisticRegression()
logreg.fit(x_train, y_train)

y_pred = logreg.predict(x_test)
acc = accuracy_score(y_test, y_pred)
print("Accuracy: ", acc)

Accuracy:  0.9444444444444444
