## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [1]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [3]:
from sklearn.model_selection import train_test_split

X_train1, X_test1, y_train1, y_test1 = train_test_split(X[:40], y[:40], test_size=10)
X_train0, X_test0, y_train0, y_test0 = train_test_split(X[40:], y[40:], test_size=10)

In [4]:
X_train = np.vstack((X_train1,X_train0))
X_test = np.vstack((X_test1,X_test0))
X_test

array([[115, 116, 117, 118, 119],
       [ 50,  51,  52,  53,  54],
       [ 20,  21,  22,  23,  24],
       [ 70,  71,  72,  73,  74],
       [  0,   1,   2,   3,   4],
       [ 40,  41,  42,  43,  44],
       [ 15,  16,  17,  18,  19],
       [155, 156, 157, 158, 159],
       [135, 136, 137, 138, 139],
       [130, 131, 132, 133, 134],
       [900, 901, 902, 903, 904],
       [250, 251, 252, 253, 254],
       [385, 386, 387, 388, 389],
       [675, 676, 677, 678, 679],
       [345, 346, 347, 348, 349],
       [945, 946, 947, 948, 949],
       [415, 416, 417, 418, 419],
       [480, 481, 482, 483, 484],
       [760, 761, 762, 763, 764],
       [310, 311, 312, 313, 314]])

In [5]:
y_train = np.hstack((y_train1,y_train0))
y_test = np.hstack((y_test1,y_test0))
y_test

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [6]:
print("Shape of X: ", X_test.shape)
print("Shape of y: ", y_test.shape)

Shape of X:  (20, 5)
Shape of y:  (20,)
